"""Songs for players

Revision ID: dfcb05cb3e22
Revises: f8a989d92e69
Create Date: 2026-04-23 12:26:20.249367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcb05cb3e22'
down_revision: Union[str, Sequence[str], None] = 'f8a989d92e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('songs', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'songs')
    # ### end Alembic commands ###
